<?xml version="1.0"?>
<!DOCTYPE xml>

<sdf xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wall" params="name x y length height thickness yaw">
    <link name='${name}_link'>
      <visual name='${name}'>
	<geometry>
	  <box>
	    <size>${length} ${thickness} ${height}</size>
	  </box>
	</geometry>
	<material>
	  <ambient>0.9 0.9 0.9 1</ambient>
	  <diffuse>0.9 0.9 0.9 1</diffuse>
	</material>
      </visual>
      <pose>${x} ${y} ${height / 2.0} 0 -0 ${yaw}</pose>
      <inertial>
	<pose>0 0 0 0 -0 0</pose>
	<mass>1</mass>
	<inertia>
	  <ixx>1</ixx>
	  <ixy>0</ixy>
	  <ixz>0</ixz>
	  <iyy>1</iyy>
	  <iyz>0</iyz>
	  <izz>1</izz>
	</inertia>
      </inertial>
    </link>	
  </xacro:macro>
</sdf>
